### ISSUE TITLE
movielens fails to install

### ISSUE THREAD

**Issue by adejanovski** [riptano/cdm-java#27]
Using Apache Cassandra 2.1.16, **movielens** fails to install because of a `date` type used for the `release_date` and `video_release_date` columns of the `movies` table : 

```
$ ./cdm install movielens
Starting CDM
Installing movielens
Checking for repo at /home/travis/.cdm/movielens
Cloning https://github.com/rustyrazorblade/movielens.git
Having repository: /home/travis/.cdm/movielens/.git
CDM is using dataset path: /home/travis/.cdm/movielens
Loading schema from /home/travis/.cdm/movielens/schema.cql
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.SystemProperties).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Dropping keyspace
 CREATE KEYSPACE movielens WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1}
Schema: /home/travis/.cdm/movielens/schema.cql
Letting schema settle...
CREATE TABLE movies (
    id uuid PRIMARY KEY,
    avg_rating float,
    genres set<text>,
    name text,
    release_date date,
    url text,
    video_release_date date
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE'
Exception in thread "main" com.datastax.driver.core.exceptions.SyntaxError: Invalid (reserved) user type name date
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:64)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:39)
	at com.datastax.cdm.CassandraDatasetManager.install(CassandraDatasetManager.java:277)
	at com.datastax.cdm.CassandraDatasetManager.main(CassandraDatasetManager.java:108)
```

**Comment by ernitingoel** [comment]
Did you find the solution for the same?
